import "./globals.css";

export const metadata = {
  title: "gsm.gg",
  description: "Generated by gsm.gg",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
